# Generated by Django 4.2.4 on 2023-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('middlename', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('dof', models.DateField(blank=True, default=None, null=True)),
                ('race', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
