# Generated by Django 4.2.4 on 2023-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_rename_dof_details_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='details',
            name='boi',
            field=models.CharField(blank=True, default=' ', max_length=500, unique=True),
        ),
    ]
