# Generated by Django 4.2.4 on 2023-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_details_address_details_boi'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
    ]
