# Generated by Django 4.2.4 on 2023-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0006_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
