# Generated by Django 4.2.4 on 2023-09-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_project_remove_skill_gif_remove_skill_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='dof',
            new_name='date_of_birth',
        ),
    ]
